name: 'international_payments_compliance_analytics'
version: '1.0'
config-version: 2

profile: 'intl_payments_compliance'

source-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

seeds:
  +schema: INTL_PAYMENTS_COMPLIANCE.RAW
  +quote_columns: false

models:
  intl_payments_compliance:
    +schema: INTL_PAYMENTS_COMPLIANCE.RAW
    staging:
      +schema: INTL_PAYMENTS_COMPLIANCE.STAGING
      +materialized: view
      +on_schema_change: append_new_columns
    int:
      +schema: INTL_PAYMENTS_COMPLIANCE.INTERMEDIATE
      +materialized: table
      +on_schema_change: append_new_columns
    marts:   
      +schema: INTL_PAYMENTS_COMPLIANCE.MART
      +materialized: table
      +on_schema_change: append_new_columns