name: 'international_payments_compliance_analytics'
version: '1.0'
config-version: 2

profile: 'intl_payments_compliance'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

seeds:
  +schema: RAW
  +quote_columns: false

models:
    staging:
      +materialized: view
      +on_schema_change: append_new_columns
    intermediate:
      +materialized: table
      +on_schema_change: append_new_columns
    marts:
      +materialized: table
      +on_schema_change: append_new_columns