version: 2

sources:
  - name: raw
    database: INTL_PAYMENTS_COMPLIANCE
    schema: RAW
    tables:
      - name: customers
        description: "Raw customer data ingested from source systems"
        columns:
          - name: id
          - name: full_name
          - name: dob
          - name: address
          - name: phone_number
          - name: bvn
          - name: nin
          - name: country_of_residence
          - name: kyc_status
          - name: created_at

models:
  - name: stg_customers
    description: "Cleaned, normalized customer data"
    columns:
      - name: customer_id
        description: "Surrogate key for customer"
        tests:
          - unique
          - not_null
      - name: full_name
        description: "Sanitized name"
        tests:
          - not_null
      - name: dob
        description: "Date of birth casted to date"
        tests:
          - not_null
      - name: address
        description: "Sanitised Customer address"
      - name: phone_number
        description: "Sanitised Customer phone number"
      - name: bvn
        description: "Sanitised Customer BVN"
      - name: nin
        description: "Sanitised Customer NIN"
      - name: country_of_residence
        description: "Normalised and sanitised ISO 3166-1 alpha-2 country codes for Country of residence"
        tests:
          - accepted_values:
              values: [
                AD, AE, AF, AG, AI, AL, AM, AO, AQ, AR, AS, AT, AU, AW, AX, AZ,
                BA, BB, BD, BE, BF, BG, BH, BI, BJ, BL, BM, BN, BO, BQ, BR, BS, BT, BV,
                BW, BY, BZ, CA, CC, CD, CF, CG, CH, CI, CK, CL, CM, CN, CO, CR, CU, CV,
                CW, CX, CY, CZ, DE, DJ, DK, DM, DO, DZ, EC, EE, EG, EH, ER, ES, ET, FI,
                FJ, FK, FM, FO, FR, GA, GB, GD, GE, GF, GG, GH, GI, GL, GM, GN, GP, GQ,
                GR, GS, GT, GU, GW, GY, HK, HM, HN, HR, HT, HU, ID, IE, IL, IM, IN, IO,
                IQ, IR, IS, IT, JE, JM, JO, JP, KE, KG, KH, KI, KM, KN, KP, KR, KW, KY,
                KZ, LA, LB, LC, LI, LK, LR, LS, LT, LU, LV, LY, MA, MC, MD, ME, MF, MG,
                MH, MK, ML, MM, MN, MO, MP, MQ, MR, MS, MT, MU, MV, MW, MX, MY, MZ, NA,
                NC, NE, NF, NG, NI, NL, NO, NP, NR, NU, NZ, OM, PA, PE, PF, PG, PH, PK,
                PL, PM, PN, PR, PS, PT, PW, PY, QA, RE, RO, RS, RU, RW, SA, SB, SC, SD,
                SE, SG, SH, SI, SJ, SK, SL, SM, SN, SO, SR, SS, ST, SV, SX, SY, SZ, TC,
                TD, TF, TG, TH, TJ, TK, TL, TM, TN, TO, TR, TT, TV, TW, TZ, UA, UG, UM,
                US, UY, UZ, VA, VC, VE, VG, VI, VN, VU, WF, WS, YE, YT, ZA, ZM, ZW
              ]
      - name: kyc_status
        description: "Normalised and sanitised KYC status of the customer"
      - name: created_at
        description: "Timestamp when the customer record was created"
        tests:
          - not_null
      - name: for_review
        description: "Flag for records needing manual attention"
        tests:
          - not_null
      - name: id_issue
        description: "Flag for records with missing or invalid customer_id_raw"
        tests:
          - not_null
